##------------------------------------------------
##   Listeners
##------------------------------------------------
[[listener]]
protocol = "tcp"
addr = "[::]:1883"
proxy_protocol = false
max_connections = 102400

[[listener]]
protocol = "tls"
addr = "[::]:8883"
cert = "./config/iotmq.crt"
key = "./config/iotmq.key"

[[listener]]
protocol = "ws"
addr = "0.0.0.0:8083"

[[listener]]
protocol = "wss"
addr = "0.0.0.0:8084"
cert = "./config/iotmq.crt"
key = "./config/iotmq.key"

##------------------------------------------------
##   MQTT
##------------------------------------------------
[mqtt]
max_client_id_len = 0
max_packet_size = 0
max_topic_alias = 65535
max_receive = 2048
max_qos = 2
max_inflight = 16
max_queue_len = 1000
session_expiry_interval = 300
retain_available = true

##------------------------------------------------
##   Web
##------------------------------------------------
[web]
addr = "[::]:8080"

##------------------------------------------------
##   Log
##------------------------------------------------
[log.file]
level = "info"                  # trace | debug | info | warn | error , default: info
format = "json"                 # json | text , default: json
dir = "./logs"                  # log file directory, default: ./logs
filename = "iotmq.log"          # log filename , default: iotmq.log
error_filename = "error.log"    # error log filename, default: error.log
rotation_size = 100             # rotation log file size (MB) , default: 100
rotation_days = 30              # log file retention days , default: 30

[log.console]
enable = true      # enable console log , default: false
level = "debug"     # trace | debug | info | warn | error , default: warn
format = "text"    # json | text , default: text

##------------------------------------------------
##   Cluster
##------------------------------------------------
[cluster]
node_id = 1
node_port = 6666
peer_addrs = ["1@127.0.0.1", "2@127.0.0.1"]
